app = 'entitydecode-com'
primary_region = 'iad'

[deploy]
strategy = "rolling"

[http_service]
internal_port = 8043
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[http_service.concurrency]
hard_limit = 500
soft_limit = 450
# [[http_service.checks]]
# grace_period = '1s'
# interval = '10s'
# method = 'GET'
# timeout = '1s'
# path = '/health'

[[statics]]
guest_path = '/srv/http/_astro'
url_prefix = '/_astro'
