on:
  pull_request:

concurrency:
  group: build-${{ forgejo.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: build
        run: npm run build
