on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ forgejo.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: deploy
        run: bun run deploy
        env:
          BUNNYNET_API_KEY: ${{ secrets.BUNNYNET_API_KEY }}
