// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func about() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button class=\"btn btn-ghost no-animation mx-auto block\" @click=\"open = !open\">About</button><div class=\"space-y-2 w-full\" x-transition x-cloak x-show=\"open\"><p><strong>Entity</strong>Decode is a tool to change any escaped characters, such as  <code>%24</code> in URLs, and HTML entities such as <code>&amp;raquo;</code> into their proper characters (you can try both of those down below if you want!).</p><p>You can use this to decode any HTML Entities, or URL Encodings, and make them more readable, by pasting/typing it into the  <label for=\"encode\" class=\"label inline link\">Encoded</label> Textbox.</p><p>It also works the other way, you can paste/type anything you want to convert into an HTML Entity into the  <label for=\"decode\" class=\"label inline link\">Decoded</label> Textbox.</p><p>If you have no idea what I'm on about, with <a target=\"_blank\" class=\"link link-primary\" href=\"https://en.wikipedia.org/wiki/Character_encodings_in_HTML#Character_references\">HTML Entities</a> and  <a target=\"_blank\" class=\"link link-primary\" href=\"https://en.wikipedia.org/wiki/Percent-encoding\">URL Encodings</a> , click the respective links to view more information about them.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
