// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Layout(slot templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"description\" content=\"EntityDecode is a tool to change any escaped characters into their proper characters\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>EntityDecode</title><link rel=\"icon\" type=\"image/png\" href=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+gDCxYwLFNXS0wAAAHdSURBVEjH7ZUxaNRgGIaf74jlCFKkiMi1HCLiUK4d6uHUSToUkQ5FHJz6g4Ojg0jp5CBOxdlBSKcO0qkcxaGIHMVBTpEiIofIIUXkkBLCEUII+RzuuP7NEcHc4uA/BP4vb54/3/u9IaLCWKs03uP/AkCuTfOcWzl3G9yfu8i7U8f09IM02PE6/a2jKXGej5pISkrEMW2NByfOy3UWqJv1PsIZqpscjBC+EALwWjclGNQWmeeOrkpg1r1jG7Cvz0b6S1uRATSUI8/v18xL9jiQTVZ4w7YNSN+HuUZZHngJPg2TsMtts+91C07Be8UnZpkdZ4x7zFAdA6BNJrhkyiceuPXLGU3Er1acS/hBQAULsMZyRvKZJ7RzjU00kCkmTgAVKhlNgvuHFhLpUaLkWPLs60ak+QBJiUGtHDxuPf0rFx09K8gYY3RkkpCkOMBlki5x8RzUKHNE6BQFyE3t8m2raAumyg35Ku2CUTZTPMTlrXbsz9mtnx9RJgRzgJ2HtbJUecBdvrO9FdmADTZGAG1WAPSKrJreoPd71LigP+WRdwjgiA3JrhIo4sgSS8NarL40eeHt9rcOEBPlAKLB1Y70R2myw+FwGgtnZIZzuYBODbl6yuoAH98bIuX/v5HfAHuYhYAOprwAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjQtMDMtMTFUMjI6NDg6NDQrMDA6MDCInEHwAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI0LTAzLTExVDIyOjQ4OjQ0KzAwOjAw+cH5TAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNC0wMy0xMVQyMjo0ODo0NCswMDowMK7U2JMAAAAASUVORK5CYII=\"><link rel=\"stylesheet\" href=\"/assets/app.css\"><style>[x-cloak] { display: none !important; }</style><script defer type=\"application/javascript\" src=\"/assets/app.js\"></script></head><!--   --><body class=\"flex flex-col w-full max-w-screen-xl m-auto gap-4 p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = slot.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"text-sm text-center\"><p>Source Code: <a class=\"link\" href=\"https://github.com/RobBrazier/entitydecode.com\">GitHub</a></p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
