when:
  - branch: main
    event: push

steps:
  - name: build
    when:
      - event: push
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build
      frozen_lockfile: true
  - name: deploy
    when:
      - event: push
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: deploy
      frozen_lockfile: true
    environment:
      BUNNYNET_API_KEY:
        from_secret: BUNNYNET_API_KEY
