when:
  - branch: main
    event: push

steps:
  - name: build
    image: denoland/deno:latest
    when:
      - event: push
    commands:
      - deno install
      - deno task build
  - name: deploy
    image: denoland/deno:latest
    when:
      - event: push
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_WORKERS_API_TOKEN
    commands:
      - deno task deploy
