when:
  - branch: main
    event: push

steps:
  - name: build
    image: node:lts-alpine
    when:
      - event: push
    commands:
      - npm ci
      - npm run build
  - name: deploy
    image: node:lts-alpine
    when:
      - event: push
    environment:
      BUNNYNET_API_KEY:
        from_secret: BUNNYNET_API_KEY
    commands:
      - npx -y @bunny.net/cli sites deploy dist
