name: deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.1.11
      - run: |
          bun install
          bun run build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: ./dist
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: dist
          path: dist
      - uses: ayeressian/bunnycdn-storage-deploy@74f4ef4922470087621a4d134f7960b74492e8fc # v2.3.0
        with:
          source: "dist"
          storageZoneName: "${{ secrets.BUNNY_STORAGE }}"
          storagePassword: "${{ secrets.BUNNY_API_STORAGE }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
