name: deploy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.1.11
      - run: |
          bun install
          bun run build
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: dist
          path: ./dist
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: dist
          path: dist
      - uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "dist"
          storageZoneName: "${{ secrets.BUNNY_STORAGE }}"
          storagePassword: "${{ secrets.BUNNY_API_STORAGE }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
